# Generated by Django 2.1.5 on 2021-10-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211025_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_height',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='item',
            name='image_width',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='product_images', width_field='image_width'),
        ),
    ]
