# Generated by Django 2.1.15 on 2021-11-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(blank=True, null=True, to='shop.OrderItem'),
        ),
    ]
