# Generated by Django 2.1.15 on 2021-11-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211102_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='C:/Users/daniel/Workspace/ecommerce/media/product_images/white_tshirt.jpg', height_field='image_height', upload_to='product_images', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_height',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_width',
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(related_name='orderitems', to='shop.OrderItem'),
        ),
    ]
