# Generated by Django 2.1.15 on 2021-11-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211102_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(default='C:\\Users\\daniel\\Workspace\\ecommerce\\media\\homepage_images\\autum1.jpg', upload_to='homepage_images')),
                ('slogan_line1', models.CharField(default='READY FOR', max_length=100)),
                ('slogan_line2', models.CharField(blank=True, default='WINTER?', max_length=100, null=True)),
                ('slogan_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('category_image1', models.ImageField(default='C:\\Users\\daniel\\Workspace\\ecommerce\\media\\feature_product\\shirt1_square.jpg', upload_to='feature_product')),
                ('category_image2', models.ImageField(default='C:\\Users\\daniel\\Workspace\\ecommerce\\media\\feature_product\\jean1_square.jpg', upload_to='feature_product')),
                ('category_image3', models.ImageField(default='C:\\Users\\daniel\\Workspace\\ecommerce\\media\\feature_product\\dress1_square.jpg', upload_to='feature_product')),
                ('category1', models.CharField(default='shirt', max_length=100)),
                ('category2', models.CharField(default='trousers', max_length=100)),
                ('category3', models.CharField(default='dress', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='C:\\Users\\daniel\\Workspace\\ecommerce\\media\\product_images\\white_tshirt.jpg', height_field='image_height', upload_to='product_images', width_field='image_width'),
        ),
    ]
