# Generated by Django 2.1.15 on 2021-11-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211104_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addr1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addr2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addr3',
            new_name='address_line3',
        ),
    ]
