# Generated by Django 2.1.15 on 2021-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_navbar_dropdown_category_navbar_dropdown_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=20),
        ),
    ]
