# Generated by Django 2.1.15 on 2021-11-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_item_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='product_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Gender_choice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Season_choice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Type_choice'),
        ),
    ]
