# Generated by Django 2.1.15 on 2021-11-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20211122_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_choice',
            name='product_gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('neutral', 'neutral'), ('kid', 'kids')], default='female', max_length=20),
        ),
    ]
