# Generated by Django 2.1.15 on 2021-11-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20211124_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_choice',
            name='product_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Gender_choice'),
        ),
    ]
