# Generated by Django 2.1.15 on 2021-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20211125_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_choice',
            name='show_in_all_category',
            field=models.BooleanField(default=False),
        ),
    ]
