# Generated by Django 2.1.15 on 2021-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_type_choice_show_in_all_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('google_play', models.URLField()),
                ('paypal_account', models.CharField(max_length=200)),
            ],
        ),
    ]
