# Generated by Django 3.2.9 on 2021-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20211125_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us_config',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_us'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_images'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category_image1',
            field=models.ImageField(blank=True, null=True, upload_to='feature_product'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category_image2',
            field=models.ImageField(blank=True, null=True, upload_to='feature_product'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category_image3',
            field=models.ImageField(default='/media//feature_product/jean1_square.jpg', upload_to='feature_product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media//product_images/white_tshirt.jpg', height_field='image_height', upload_to='product_images', width_field='image_width'),
        ),
    ]
