# Generated by Django 3.2.9 on 2021-11-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20211127_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_config',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate1_type', to='shop.type_choice'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate2_type', to='shop.type_choice'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate3_type', to='shop.type_choice'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category_image3',
            field=models.ImageField(blank=True, null=True, upload_to='feature_product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='product_images', width_field='image_width'),
        ),
    ]
