# Generated by Django 3.2.9 on 2021-11-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20211127_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_config',
            name='category1',
            field=models.CharField(choices=[('tee', 't-shirt'), ('shirt', 'shirt'), ('jean', 'jeans'), ('dress', 'dresses'), ('trousers', 'trousers'), ('jacket', 'coats and jackets')], default='shirt', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category2',
            field=models.CharField(choices=[('tee', 't-shirt'), ('shirt', 'shirt'), ('jean', 'jeans'), ('dress', 'dresses'), ('trousers', 'trousers'), ('jacket', 'coats and jackets')], default='trousers', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category3',
            field=models.CharField(choices=[('tee', 't-shirt'), ('shirt', 'shirt'), ('jean', 'jeans'), ('dress', 'dresses'), ('trousers', 'trousers'), ('jacket', 'coats and jackets')], default='dress', max_length=100),
        ),
    ]
