# Generated by Django 3.2.9 on 2021-11-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20211127_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_config',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate1_type', to='shop.type_choice'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate2_type', to='shop.type_choice'),
        ),
        migrations.AlterField(
            model_name='homepage_config',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate3_type', to='shop.type_choice'),
        ),
    ]
