# Generated by Django 3.2.9 on 2021-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_shop_config_shop_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
